name: yivi-business-wallet

services:
  backend:
    build:
      context: backend
      dockerfile: docker/production/Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: src/docker/development/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
