services:
  db:
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: docker/development/Dockerfile
    volumes:
      - ./backend:/app
      - backend-go-build:/root/.cache/go-build
      - backend-go-mod:/go/pkg/mod

  migrate:
    build:
      dockerfile: docker/development/Dockerfile
    entrypoint: [ "go", "run", "./cmd/migrate"]
    volumes:
      - ./backend:/app
      - backend-go-build:/root/.cache/go-build
      - backend-go-mod:/go/pkg/mod

  frontend:
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules

volumes:
  backend-go-build:
  backend-go-mod:
  frontend-node-modules:
