// Package diploma verifies and reads the digital diploma extracts that DUO
// (Dienst Uitvoering Onderwijs) issues from the Dutch diploma register
// ("Mijn diploma's", register onderwijsdeelnemers).
package diploma

import (
	"strings"
	"time"
)

// Document holds the data printed on a DUO diploma extract.
type Document struct {
	// The heading of the extract: "Diploma" or "Getuigschrift" (certificate,
	// e.g. a propaedeutic certificate), as printed but title cased.
	DocumentType string `json:"document_type"`
	// Name of the qualification, e.g. "Hoger algemeen voortgezet onderwijs"
	// or "HBO Bachelor Informatica Propedeuse".
	Qualification string `json:"qualification"`
	// Profiles (profielen) listed under "PROFIEL", e.g. "Natuur en Techniek".
	// Empty for most qualifications.
	Profiles []string `json:"profiles"`
	// The holder as printed under "BEHAALD DOOR": given names and surname as
	// one line, e.g. "Anna Maria van der Berg". DUO does not split the name.
	FullName string `json:"full_name"`
	// "Geboren op": date of birth of the holder.
	DateOfBirth time.Time `json:"date_of_birth"`
	// The institution under "UITGEGEVEN DOOR".
	Institution string `json:"institution"`
	// Place printed before the award date, e.g. "Arnhem".
	PlaceOfIssue string `json:"place_of_issue"`
	// The date the diploma was awarded.
	DateAwarded time.Time `json:"date_awarded"`
	// Level from "Dit diploma heeft niveau NLQF 4 / EQF 4."; empty when the
	// extract does not print a level.
	NLQFLevel string `json:"nlqf_level"`
	EQFLevel  string `json:"eqf_level"`
	// "Downloaddatum": the day the extract was generated by DUO.
	DownloadDate time.Time `json:"download_date"`
	// The number DUO prints in the footer ("2896311 - pagina 1/1").
	DocumentNumber string `json:"document_number"`
	// Number of pages of the extract.
	Pages int `json:"pages"`
	// True when the extract includes the list of grades (cijferlijst).
	HasGradeList bool `json:"has_grade_list"`
}

// ProfilesString renders the profiles as one attribute value: "Natuur en
// Techniek; Natuur en Gezondheid".
func (d *Document) ProfilesString() string {
	return strings.Join(d.Profiles, "; ")
}
